name: Auto Approve

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'pandamelive'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
